create or replace PROCEDURE XBCM_MIGRATE IS
BEGIN 
insert into tbl_SUPPLIER
(SUPP_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL)
Select Distinct SUPPLIER_NAME,SUPP_CONTACT_NAME,SUPP_ADDRESS,SUPP_CONTACT_NUMBER,SUPP_EMAIL
from XXBCM_ORDER_MGT;

insert into tbl_ORDER
(ORDER_REF, SUPP_ID)
Select Distinct ORDER_REF,(SELECT Distinct SUPP_ID FROM tbl_supplier a WHERE 
a.SUPP_NAME = b.SUPPLIER_NAME and a.SUPP_CONTACT_NAME = b.SUPP_CONTACT_NAME  and a.supp_address= b.SUPP_ADDRESS and a.SUPP_CONTACT_NAME = b.SUPP_CONTACT_NAME and a.SUPP_EMAIL = b.SUPP_EMAIL )
from XXBCM_ORDER_MGT b; 

insert into tbl_ORDER_LIST
(ORDER_ID,ORD_L_DATE,ORD_L_TOTAL_AMOUNT,ORD_L_DESCRIPTION,ORD_L_STATUS,ORD_L_LINE_AMOUNT)
Select Distinct (SELECT Distinct  ORDER_ID FROM tbl_order a WHERE 
a.ORDER_REF = b. ORDER_REF),TO_DATE(ORDER_DATE,'DD-MON-YYYY'),ORDER_TOTAL_AMOUNT,ORDER_DESCRIPTION ,ORDER_STATUS,ORDER_LINE_AMOUNT
from XXBCM_ORDER_MGT b; 

insert into tbl_INVOICE
(INVOICE_REFERENCE)
Select Distinct INVOICE_REFERENCE 
from XXBCM_ORDER_MGT; 

insert into tbl_INV_order
(INV_ID, ORDER_ID)
Select Distinct INVOICE_REFERENCE,  ORDER_REF ,(SELECT Distinct  ORDER_ID FROM tbl_order a WHERE 
a.ORDER_REF = b. ORDER_REF), (SELECT Distinct  INV_ID FROM tbl_INVOICE c WHERE c.INV_REFERENCE = b.INVOICE_REFERENCE)
from XXBCM_ORDER_MGT b; 

insert into tbl_INVOICE_LIST
(INV_L_DATE,INV_L_STATUS, INV_L_HOLD_REASON,INV_L_AMOUNT,INV_L_DESCRIPTION)
Select Distinct TO_DATE(INVOICE_DATE,'DD-MON-YYYY'),INVOICE_STATUS,INVOICE_HOLD_REASON,INVOICE_AMOUNT,INVOICE_DESCRIPTION, (SELECT Distinct  INV_ID FROM tbl_INVOICE a WHERE a.INV_REFERENCE = b.INVOICE_REFERENCE)
from XXBCM_ORDER_MGT b; 

end XBCM_MIGRATE;



