create or replace PROCEDURE X_QUES5 IS
BEGIN

SELECT * FROM (
  SELECT
    TRIM(BOTH(REGEXP_REPLACE(ORDER_REF, '[^0-9A-Za-z ]+', '.')) AS 'Order Ref',
    (ORD_L_DATE(CHECKED_DATE,'dd/mm/yyyy'),'MONTH dd, yyyy')) AS 'Order Date',
    UPPER(TBL_SUPPLIER.SUPP_NAME) AS 'Supplier Name',
    to_char(ORD_L_TOTAL_AMOUNT, '99,999,990.00') AS 'Order Amount',
    ORD_L_STATUS,
    (
        SELECT  LISTAGG(INV_REFERENCE,',') 
        WITHIN GROUP( ORDER BY INV_REFERENCE ) 
        FROM TBL_INVOICE
        JOIN TBL_INV_ORDER ON TBL_INVOICE.INV_ID = TBL_INV_ORDER.INV_ID
        WHERE TBL_INV_ORDER.ORDER_ID = ORDER_ID
    ) AS 'Invoice References',
 OVER (ORDER BY ORD_L_TOTAL_AMOUNT Desc)r
  FROM TBL_ORDER_LIST
  JOIN TBL_ORDER ON TBL_ORDER.ORDER_ID = TBL_ORDER_LIST.ORDER_ID
  JOIN TBL_SUPPLIER ON TBL_SUPPLIER.SUPP_ID = TBL_ORDER.SUPP_ID
 
) 
WHERE r = 3

end X_QUES5 ;